name: molkkycount
description: Count Molkky is now a child game
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ">=3.1.0-163.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo_192.png
    - lib/assets/logo_1000.png
