name: molkkycount
description: Count Molkky is now a child game
publish_to: 'none'
version: 1.2.3

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  url_launcher: ^6.1.11
  dropdown_button2: ^2.3.8
  flutter_vortezz_base:
    path: ../flutter_vortezz_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_192.png
    - assets/logo_1000.png
    - assets/lang/en.json
    - assets/lang/fr.json
    - assets/lang/de.json
    - assets/lang/es.json
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/OpenSans-Regular.ttf
          weight: 300